# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2020-03-07 08:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attendence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(null=True)),
                ('morningattendence', models.CharField(max_length=200, null=True)),
                ('nightattendence', models.CharField(max_length=200, null=True)),
                ('guestname', models.CharField(max_length=200, null=True)),
                ('guestmno', models.IntegerField(null=True)),
                ('guestintime', models.TimeField(null=True)),
                ('guestouttime', models.TimeField(null=True)),
                ('schoolouttime', models.TimeField(null=True)),
                ('schoolintime', models.TimeField(null=True)),
                ('personalvisit', models.CharField(max_length=200, null=True)),
                ('pvouttime', models.TimeField(null=True)),
                ('pvintime', models.TimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Branches',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branchname', models.CharField(max_length=200)),
                ('ownername', models.CharField(max_length=200)),
                ('branchid', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('village', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=200)),
                ('state', models.CharField(max_length=200)),
                ('phoneno', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Children',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('childid', models.IntegerField()),
                ('childname', models.CharField(max_length=200)),
                ('childdob', models.DateField()),
                ('gender', models.CharField(max_length=200)),
                ('photo', models.ImageField(null=True, upload_to='')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='govnportal.Branches')),
            ],
        ),
        migrations.CreateModel(
            name='DCPUlogin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Donations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donationid', models.IntegerField(null=True)),
                ('donorname', models.CharField(max_length=200)),
                ('phoneno', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=500)),
                ('informof', models.CharField(max_length=100)),
                ('amount', models.IntegerField(null=True)),
                ('foodtime', models.CharField(max_length=100, null=True)),
                ('date', models.DateField(null=True)),
                ('receipt', models.FileField(upload_to='')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='govnportal.Branches')),
            ],
        ),
        migrations.CreateModel(
            name='Funds',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fundid', models.IntegerField()),
                ('fundfor', models.CharField(max_length=200)),
                ('fundraisedby', models.CharField(max_length=200)),
                ('amount', models.IntegerField()),
                ('paymentmode', models.CharField(max_length=200)),
                ('paymentimage', models.ImageField(upload_to='')),
                ('date', models.DateField(null=True)),
                ('balance', models.IntegerField(null=True)),
                ('completestatus', models.CharField(max_length=200, null=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='govnportal.Branches')),
            ],
        ),
        migrations.CreateModel(
            name='Fundusagebills',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill', models.ImageField(upload_to='')),
                ('fund', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='govnportal.Funds')),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orgname', models.CharField(max_length=200)),
                ('ownername', models.CharField(max_length=200)),
                ('orgid', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('village', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=200)),
                ('state', models.CharField(max_length=200)),
                ('phoneno', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problemname', models.CharField(max_length=200)),
                ('problemdes', models.CharField(max_length=10000)),
                ('problemid', models.IntegerField()),
                ('photo', models.ImageField(null=True, upload_to='')),
                ('date', models.DateField()),
                ('orgacceptance', models.CharField(max_length=100)),
                ('solved', models.CharField(max_length=100)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='govnportal.Branches')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='govnportal.Organization')),
            ],
        ),
        migrations.CreateModel(
            name='Problemsolution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problemsolution', models.CharField(max_length=1000)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='govnportal.Branches')),
                ('fund', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='govnportal.Funds')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='govnportal.Organization')),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='govnportal.Problem')),
            ],
        ),
        migrations.AddField(
            model_name='funds',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='govnportal.Organization'),
        ),
        migrations.AddField(
            model_name='funds',
            name='problem',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='govnportal.Problem'),
        ),
        migrations.AddField(
            model_name='donations',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='govnportal.Organization'),
        ),
        migrations.AddField(
            model_name='branches',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='govnportal.Organization'),
        ),
        migrations.AddField(
            model_name='attendence',
            name='branch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='govnportal.Branches'),
        ),
        migrations.AddField(
            model_name='attendence',
            name='child',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='govnportal.Children'),
        ),
    ]
