# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2020-03-07 08:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('govnportal', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fundusagebills',
            name='fund',
        ),
        migrations.DeleteModel(
            name='Fundusagebills',
        ),
    ]
