# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2020-03-07 08:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('govnportal', '0002_auto_20200307_1406'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fundusagebills',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill', models.ImageField(upload_to='')),
                ('fund', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='govnportal.Funds')),
            ],
        ),
    ]
