# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2020-03-07 11:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('govnportal', '0004_fundusagebills_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='fundusagebills',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
