# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2020-04-01 09:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('govnportal', '0005_fundusagebills_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='branches',
            name='balance',
            field=models.IntegerField(null=True),
        ),
    ]
