# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2020-04-08 11:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('govnportal', '0006_branches_balance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fundusagebills',
            name='fund',
        ),
        migrations.DeleteModel(
            name='Fundusagebills',
        ),
    ]
