from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^dcpu$', views.dcpulogin, name='dcpulogin'),
    url(r'^dcpu/home$', views.dcpuhome, name='dcpuhome'),
    url(r'^dcpu/branches/$', views.viewbranches, name='viewbranches'),
    url(r'^logout/$', views.logouttoindex, name='logout'),
    url(r'^dcpu/orgregister/$', views.addorganization, name='addorg'),
    url(r'^dcpu/orgregistered$', views.orgindata, name='orgindata'),
    url(r'^dcpu/viewattendance$', views.dcpuviewattendance, name='dcpuviewattendance'),
    url(r'^dcpu/viewprobs$', views.viewprobs, name='viewprobs'),
    url(r'^dcpu/viewattendance/branch$', views.dcpuviewatt_getbranch, name='dcpuviewatt_getbranch'),
    url(r'^dcpu/dcpuraisefund$', views.dcpuraisefund, name='dcpuraisefund'),
    url(r'^dcpu/dcpuraisefund/getbranch$', views.dcpuraisefund_getbranch, name='dcpuraisefund_getbranch'),
    url(r'^dcpu/dcpusolvedprobs$', views.dcpusolvedprobs, name='dcpusolvedprobs'),
    url(r'^dcpu/dcpuraisedfund$', views.dcpuraisedfund, name='dcpuraisedfund'),
    url(r'^dcpu/dcpuviewbills$', views.dcpuviewbills, name='dcpuviewbills'),
    url(r'^org$', views.orglogin, name='orglogin'),
    url(r'^org/home$', views.orghome, name='orghome'),
    url(r'^org/orgviewattendence$', views.orgviewattendence, name='orgviewattendence'),
    url(r'^org/branchregister/$', views.addbranch, name='addbranch'),
    url(r'^org/branchregistered$', views.branchindata, name='branchindata'),
    url(r'^org/orgviewprobs$', views.orgviewprobs, name='orgviewprobs'),
    url(r'^org/orgviewprobs/orgsolution$', views.orgsolution, name='orgsolution'),
    url(r'^org/orgraisefund$', views.orgraisefund, name='orgraisefund'),
    url(r'^org/orgsolvedprobs$', views.orgsolvedprobs, name='orgsolvedprobs'),
    url(r'^org/orgraisedfund$', views.orgraisedfund, name='orgraisedfund'),
    url(r'^branch$', views.branchlogin, name='branchlogin'),
    url(r'^branch/home$', views.branchhome, name='branchhome'),
    url(r'^branch/childregister/$', views.addchild, name='addchild'),
    url(r'^branch/uploadattendence$', views.uploadattendence, name='uploadattendence'),
    url(r'^branch/guestvisit$', views.guestvisit, name='guestvisit'),
    url(r'^branch/delguest$', views.delguest, name='delguest'),
    url(r'^branch/personalvisit$', views.personalvisit, name='personalvisit'),
    url(r'^branch/delvisit$', views.delvisit, name='delvisit'),
    url(r'^branch/viewattendence$', views.viewattendence, name='viewattendence'),
    url(r'^branch/schoolvisit$', views.schoolvisit, name='schoolvisit'),
    url(r'^branch/schoolvisitcomplete$', views.schoolvisitcomplete, name='schoolvisitcomplete'),
    url(r'^branch/uploadproblem$', views.uploadproblem, name='uploadproblem'),
    url(r'^branch/unsolvedprob$', views.unsolvedprob, name='unsolvedprob'),
    url(r'^branch/solvedprob$', views.solvedprob, name='solvedprob'),
    url(r'^branch/donations$', views.donations, name='donations'),
    url(r'^branch/viewdonations$', views.viewdonations, name='viewdonations'),
    url(r'^branch/branchraisedfunds$', views.branchraisedfunds, name='branchraisedfunds'),
    url(r'^branch/spentbills$', views.spentbills, name='spentbills'),
    url(r'^branch/uploadedbills$', views.uploadedbills, name='uploadedbills'),
    url(r'^branch/uploadbills$', views.uploadbills, name='uploadbills'),
]

